// export const examResponse = {
//   status: "OK",
//   message: null,
//   data: {
//     id: "d5315e5c-f77d-42f9-b6c4-0b9ebd903163",
//     examCode: "Q24001",
//     name: "test",
//     description: "moo tarra",
//     isOpen: false,
//     classCodes: ["CLASS3", "CLASS4"],
//     time: 60,
//     effectiveDate: 1,
//     expirationDate: 2,
//     questionAmount: 15,
//     randomAmount: 2,
//     limitation: 100,
//     pointType: 0,
//     createdBy: "hoangcm22.it@gmail.com",
//     updatedBy: "hoangcm22.it@gmail.com",
//     createdDate: 1732549711509,
//     updatedDate: 1732549711509,
//   },
//   success: true,
// };
export const examData = {
  status: "OK",
  message: null,
  data: {
    id: "5984c2b9-f12a-4dd1-b9a7-64d1ef29b77b",
    code: "Q24001",
    name: "test",
    description: "moo tarra",
    questions: [
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "7920a2c9-26e4-4064-8445-9d4127551252",
            index: null,
            answer: "Chạy tiếp theo thanh quản từ bờ dưới sụn nhẫn",
            correct: false,
            questionCode: "Q24001",
            attachmentPath: null,
          },
          {
            id: "18035cf7-b31d-448b-acde-558213667364",
            index: null,
            answer: "Từ ngang mức đốt sống cổ V đến đĩa gian đốt sống N IV-V",
            correct: false,
            questionCode: "Q24001",
            attachmentPath: null,
          },
          {
            id: "fa344f41-4cd9-48cf-90a3-358b8d84c38a",
            index: null,
            answer: "Tạo bởi các vòng sụn xếp chồng lên nhau",
            correct: false,
            questionCode: "Q24001",
            attachmentPath: null,
          },
          {
            id: "ec34291c-5e12-46ca-ad2b-7b19fdfb6e4d",
            index: null,
            answer: "Tận hết tại cựa khí quản",
            correct: false,
            questionCode: "Q24001",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chọn câu sai về khí quản?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "8e0e0b30-0ba7-4531-965b-5eaf1a054ad9",
            index: null,
            answer: "Bên phải rộng hơn, ngắn hơn, thẳng đứng hơn bên trái",
            correct: false,
            questionCode: "Q24011",
            attachmentPath: null,
          },
          {
            id: "6e333a97-20e7-4fea-9a88-23f44811684a",
            index: null,
            answer: "Dị vật đường thở thường rơi vào phế quản chính trái",
            correct: false,
            questionCode: "Q24011",
            attachmentPath: null,
          },
          {
            id: "3c558b7f-1f87-4a0f-8901-8b58cd4ccec8",
            index: null,
            answer: "Sau khi vào rốn phổi, phế quản chính phải tách ra 3 nhánh",
            correct: false,
            questionCode: "Q24011",
            attachmentPath: null,
          },
          {
            id: "562d71b6-eb8b-40e5-861f-fc36a9cc3a2a",
            index: null,
            answer: "Sau khi vào rốn phổi, phế quản chính trái tách ra 3 nhánh",
            correct: false,
            questionCode: "Q24011",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chọn câu đúng về phế quản chính?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "3cdbee44-bb94-43c0-8055-47dad44d07e6",
            index: null,
            answer: "3 cm – 4 cm – 5cm C. 5 cm – 3 cm – 4 cm",
            correct: false,
            questionCode: "Q24021",
            attachmentPath: null,
          },
          {
            id: "0d2a8267-c225-417b-bc0b-4acd91dae5f6",
            index: null,
            answer: "4 cm – 3 cm – 5 cm D. 5 cm – 4 cm – 3 cm",
            correct: false,
            questionCode: "Q24021",
            attachmentPath: null,
          },
        ],
        explain: null,
        question:
          "Điểm cao nhất của đỉnh phổi nhô lên trên đầu trước xương sườn I, xương đòn, cách",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "6a50a91e-28a4-4be8-94f8-5d87b5046b41",
            index: null,
            answer: "Gân trung tâm là nguyên ủy của cơ hoành",
            correct: false,
            questionCode: "Q24031",
            attachmentPath: null,
          },
          {
            id: "99a2b612-1c44-41bc-a10e-d3c622b329e4",
            index: null,
            answer: "Lỗ ĐM chủ nằm ngang mức bờ dưới đốt sống N XII",
            correct: false,
            questionCode: "Q24031",
            attachmentPath: null,
          },
          {
            id: "2020d0ce-e9fd-4f32-af5c-1e605fd30d76",
            index: null,
            answer:
              "Bờ gân trong trụ phải, trụ trái tạo nên dây chằng cung giữa",
            correct: false,
            questionCode: "Q24031",
            attachmentPath: null,
          },
          {
            id: "867213e6-5962-48a4-b6e4-6611fab5ba2a",
            index: null,
            answer: "Là cơ hô hấp",
            correct: false,
            questionCode: "Q24031",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chọn câu sai về cơ hoành?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "194c5235-ed61-4e2d-be16-6f5b24d2ab9d",
            index: null,
            answer: "Nằm giữa 2 lá của ngoại tâm mạc sợi",
            correct: false,
            questionCode: "Q24041",
            attachmentPath: null,
          },
          {
            id: "2dcdfbe5-6931-4e9a-822e-2f3b76814a40",
            index: null,
            answer: "Là khoang thật",
            correct: false,
            questionCode: "Q24041",
            attachmentPath: null,
          },
          {
            id: "8785f9f1-9fe3-4a69-ae3d-0ce82fb1896f",
            index: null,
            answer: "Bình thường trong ổ ngoại tâm mạc không chứa dịch",
            correct: false,
            questionCode: "Q24041",
            attachmentPath: null,
          },
          {
            id: "5640a7e4-511b-46ff-94c5-feb6561b9b3d",
            index: null,
            answer: "Khi viêm gây tràn dịch ngoại tâm mạc",
            correct: false,
            questionCode: "Q24041",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chọn câu đúng về ổ ngoại tâm mạc?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "16e13304-5405-4f9f-b736-39feb1d2091f",
            index: null,
            answer: "ĐM thân cánh tay đầu C. ĐM thận phải, trái",
            correct: false,
            questionCode: "Q24051",
            attachmentPath: null,
          },
          {
            id: "70b0fa89-ed07-4649-8313-dcf5ffbf55fc",
            index: null,
            answer: "ĐM vành phải, trái D. ĐM cảnh chung phải",
            correct: false,
            questionCode: "Q24051",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "ĐM nào không phải nhánh bên của ĐM chủ?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "1fd0ef52-9726-42f7-8fb1-722aa674ad2e",
            index: null,
            answer:
              "Mạc nối nhỏ chạy từ gan tới bờ cong nhỏ dạ dày và hành tá tràng",
            correct: false,
            questionCode: "Q24061",
            attachmentPath: null,
          },
          {
            id: "7414a33c-36f2-4563-a70f-b0e30341ec15",
            index: null,
            answer: "Mạc nối lớn gồm 2 lá dùng để dự trữ mỡ",
            correct: false,
            questionCode: "Q24061",
            attachmentPath: null,
          },
          {
            id: "a163a281-1775-487b-b822-9c3a9ee7a6a9",
            index: null,
            answer:
              "Dây chằng gan – tá tràng che toàn bộ thành phần vào cửa gan",
            correct: false,
            questionCode: "Q24061",
            attachmentPath: null,
          },
          {
            id: "b430aed8-62de-431a-a09a-55c6036e70b6",
            index: null,
            answer: "Mạc treo hỗng tràng ít mỡ nhất",
            correct: false,
            questionCode: "Q24061",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chọn ý sai về phúc mạc?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "bd997aa8-f7d8-4df1-bb11-1b6ba068eb89",
            index: null,
            answer: "Mạc treo đại tràng lên C. Mạc treo đại tràng sigma",
            correct: false,
            questionCode: "Q24071",
            attachmentPath: null,
          },
          {
            id: "678070b4-d0b8-4a1f-9297-5e32b51555ad",
            index: null,
            answer: "Mạc treo ruột thừa D. Mạc treo đại tràng ngang",
            correct: false,
            questionCode: "Q24071",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Mạc treo nào không có thật?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "15928e94-53a7-40ab-8fda-5d495f748269",
            index: null,
            answer: "Ống túi mật và túi mật là đường mật phụ",
            correct: false,
            questionCode: "Q24081",
            attachmentPath: null,
          },
          {
            id: "c0fb8fe3-efd8-4b89-b889-72b83ea6ffe2",
            index: null,
            answer:
              "Đáy túi mật là điểm giao bờ ngoài cơ thẳng bụng vs bờ sườn",
            correct: false,
            questionCode: "Q24081",
            attachmentPath: null,
          },
          {
            id: "b2162295-2371-4b0a-a30a-7bc736e5e106",
            index: null,
            answer: "Ống túi mật hợp vs ống gan chung thành ống mật chủ",
            correct: false,
            questionCode: "Q24081",
            attachmentPath: null,
          },
          {
            id: "e08a2763-1e15-4814-919f-13e73dfc20ec",
            index: null,
            answer: "Có 1 đáy, 1 thân, không có cổ",
            correct: false,
            questionCode: "Q24081",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chọn ý sai về túi mật?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "4281483b-24ec-451e-942d-8ddc3a7d306d",
            index: null,
            answer: "Khuyết góc là giao bờ trái tá tràng vs bờ cong lớn",
            correct: false,
            questionCode: "Q24091",
            attachmentPath: null,
          },
          {
            id: "37fef4d6-4316-48f9-8185-c28ed3a92332",
            index: null,
            answer:
              "Bờ trái thực quản liên tiếp với bờ cong lớn tại khuyết tâm vị",
            correct: false,
            questionCode: "Q24091",
            attachmentPath: null,
          },
          {
            id: "5def17b8-873c-4a9c-b590-4dda8b104b0e",
            index: null,
            answer: "Là mặt trước của hậu cung mạc nối",
            correct: false,
            questionCode: "Q24091",
            attachmentPath: null,
          },
          {
            id: "3d7ed12c-3005-485b-aeff-67aedaa44496",
            index: null,
            answer: "Gồm 3 lớp cơ: thẳng ngoài – vòng giữa – chéo trong cùng",
            correct: false,
            questionCode: "Q24091",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chọn ý sai về dạ dày?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "9fc2f926-0d7a-448b-9325-485fcd49c614",
            index: null,
            answer: "Tách ra từ ĐM chủ bụng ở ngang đốt sống thắt lưng III",
            correct: false,
            questionCode: "Q240101",
            attachmentPath: null,
          },
          {
            id: "9b644e83-e453-42f3-bce4-e287904f2de4",
            index: null,
            answer: "Đi sang trái ĐM chủ rồi bắt chéo ĐM chậu chung trái",
            correct: false,
            questionCode: "Q240101",
            attachmentPath: null,
          },
          {
            id: "4df3acfe-bee1-4d9a-bfbe-8321e848993e",
            index: null,
            answer: "Tận cũng bởi ĐM trực tràng trên",
            correct: false,
            questionCode: "Q240101",
            attachmentPath: null,
          },
          {
            id: "c78d6ea5-49d3-48ff-b63e-9b1d5ccadbff",
            index: null,
            answer:
              "Có đường kính và kích thước lớn hơn ĐM mạc treo tràng trên",
            correct: false,
            questionCode: "Q240101",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Các mô tả sau đây về ĐM mạc treo tràng dưới đều đúng, trừ:",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "41e3920f-07b7-4727-8757-d51ab2cab195",
            index: null,
            answer: "Ống mật chủ C. TM mạc treo tràng trên",
            correct: false,
            questionCode: "Q240111",
            attachmentPath: null,
          },
          {
            id: "20c2cf69-5557-4000-b126-6ef9ba049d39",
            index: null,
            answer: "TM cửa D. Ống tụy E. Bóng gan-tụy",
            correct: false,
            questionCode: "Q240111",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Một khối u ở mỏm móc đầu tụy có thể gây chèn ép:",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "06563ef0-06df-46cf-9f4a-2833f40d28d4",
            index: null,
            answer: "Nó có dải sán đại tràng và túi thừa mạc nối",
            correct: false,
            questionCode: "Q240121",
            attachmentPath: null,
          },
          {
            id: "1e645c18-e0bc-443c-92be-21a8aed3968c",
            index: null,
            answer:
              "Nó tiếp nhận các sợi đối giao cảm trước hạch từ TK lang thang",
            correct: false,
            questionCode: "Q240121",
            attachmentPath: null,
          },
          {
            id: "ee0c5b4d-c396-45cf-9237-445fb4d7e79a",
            index: null,
            answer: "Nó dược cấp máu bởi ĐM mạc treo tràng dưới",
            correct: false,
            questionCode: "Q240121",
            attachmentPath: null,
          },
          {
            id: "cd31e9d0-ee4a-4d22-8a78-282f3c745dc7",
            index: null,
            answer:
              "Nó hấp thu nước để biến dịch chứa bên trong thành phân đặc",
            correct: false,
            questionCode: "Q240121",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Tất cả các mô tả sau về đại tràng xuống đều đúng trừ",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "5c6ff43c-e558-419d-902c-eb21ee79aed1",
            index: null,
            answer:
              "Ít bề mặt tiêu hoá hơn C. Đường kính nhỏ hơn E. Nhung mao ít hơn",
            correct: false,
            questionCode: "Q240131",
            attachmentPath: null,
          },
          {
            id: "f736a4f5-5682-4aca-9115-80e1b9549c72",
            index: null,
            answer: "Nhung mao nhiều hơn D. Thành mỏng hơn.",
            correct: false,
            questionCode: "Q240131",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Hỗng tràng khác với hồi tràng ở điểm :",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "18ba6db0-0938-4b16-99e5-4acfd7b663d3",
            index: null,
            answer:
              "Tĩnh mạch cửa C. Động mạch gan chung E. Động mạch gan riêng",
            correct: false,
            questionCode: "Q240141",
            attachmentPath: null,
          },
          {
            id: "a4180f4d-3c35-4325-8ba2-4eaf1c3fccd3",
            index: null,
            answer: "Ống mật D. Rễ mạc nối nhỏ",
            correct: false,
            questionCode: "Q240141",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Rốn gan gồm có các thành phần sau, trừ:",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "c5db83ab-ae74-4f03-b369-22a44f436557",
            index: null,
            answer: "Thành sau liên quan đến tụy, thận trái",
            correct: false,
            questionCode: "Q240151",
            attachmentPath: null,
          },
          {
            id: "293ba114-296d-4fc0-8b2f-c96206fda13f",
            index: null,
            answer: "Thành dưới : dạ dày",
            correct: false,
            questionCode: "Q240151",
            attachmentPath: null,
          },
          {
            id: "7b83c6d2-a2ac-40fb-b6d2-9849291aa31f",
            index: null,
            answer: "Thành trái liên quan đến lách , dây chằng tụy lách",
            correct: false,
            questionCode: "Q240151",
            attachmentPath: null,
          },
          {
            id: "516d3e5e-d1bb-4757-b315-9e12319a3413",
            index: null,
            answer: "Bờ trên liên quan đến cơ hoành",
            correct: false,
            questionCode: "Q240151",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Hậu cung mạc nối có các đặc điểm sau, trừ:",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "e593ff62-879e-4497-88a2-3984529762d0",
            index: null,
            answer:
              "Nhánh phải và trái của ĐM gan, các ống gan, 2 nhánh TM cửa",
            correct: false,
            questionCode: "Q240161",
            attachmentPath: null,
          },
          {
            id: "7f350a54-4a80-4cee-8655-1092609a2177",
            index: null,
            answer:
              "Các ống gan, nhánh phải và trái của ĐM gan, 2 nhánh TM cửa",
            correct: false,
            questionCode: "Q240161",
            attachmentPath: null,
          },
          {
            id: "3e758541-8e4a-4606-8f42-e81131a4c940",
            index: null,
            answer:
              "Các ống gan, 2 nhánh TM cửa, nhánh phải và trái của ĐM gan",
            correct: false,
            questionCode: "Q240161",
            attachmentPath: null,
          },
          {
            id: "e18a00b0-d677-456b-b14e-b265dcdc5451",
            index: null,
            answer:
              "Nhánh phải và trái của ĐM gan , 2 nhánh TM cửa, các ống gan",
            correct: false,
            questionCode: "Q240161",
            attachmentPath: null,
          },
        ],
        explain: null,
        question:
          "Trình tự sắp xếp các thành phần trong cửa gan từ trước ra sau là:",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "ec20c765-ae2b-4087-9d90-d22534322ed1",
            index: null,
            answer: "Dạ dày C. Đoạn đầu tá tràng",
            correct: false,
            questionCode: "Q240171",
            attachmentPath: null,
          },
          {
            id: "99d45723-5e30-44ec-8471-e06883b43735",
            index: null,
            answer: "Góc đại tràng phải D. Dạ dày - tá tụy",
            correct: false,
            questionCode: "Q240171",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Ở mặt tạng của gan, thùy vuông liên quan tới?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "aac9e638-0afa-4375-8f78-920869c3b51a",
            index: null,
            answer:
              "Chỉ là một tuyến ngoại tiết C. Có ống tiết đổ vào tá tràng",
            correct: false,
            questionCode: "Q240181",
            attachmentPath: null,
          },
          {
            id: "1d91217e-e935-4996-a0b3-0e423e7f9a6e",
            index: null,
            answer: "Có nhiều ĐM đến cấp máu D. Do hệ TK thực vật chi phối",
            correct: false,
            questionCode: "Q240181",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Tìm ý sai về tụy?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "603275ba-3cb1-4db1-8eb9-f1e0e8d8d80c",
            index: null,
            answer: "Nhận máu từ ĐM mạc treo tràng trên",
            correct: false,
            questionCode: "Q240191",
            attachmentPath: null,
          },
          {
            id: "b10e1122-2824-4e13-b75d-74c4d16b2bfc",
            index: null,
            answer: "Được chi phối bởi một phần đám rối mạc treo tràng trên",
            correct: false,
            questionCode: "Q240191",
            attachmentPath: null,
          },
          {
            id: "178b8adf-4239-4a32-83d6-10bf20570d45",
            index: null,
            answer: "Có dịch tụy, dịch mật và dịch vị",
            correct: false,
            questionCode: "Q240191",
            attachmentPath: null,
          },
          {
            id: "b63befa3-4971-44a1-af68-9ce45d27de46",
            index: null,
            answer: "Tất cả đều đúng",
            correct: false,
            questionCode: "Q240191",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chỉ ra đặc điểm đúng nhất của ruột non?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "bce5c8ec-7bfc-46cb-9b83-c5eb3343d80e",
            index: null,
            answer: "TK chi phối cho dạ dày từ đám rối tạng và TK lang thang",
            correct: false,
            questionCode: "Q240201",
            attachmentPath: null,
          },
          {
            id: "5fd29218-34d4-432a-97ea-e3faf56b9802",
            index: null,
            answer: "Lớp cơ phân bố không đều ở tất cả các phần của dạ dày",
            correct: false,
            questionCode: "Q240201",
            attachmentPath: null,
          },
          {
            id: "373362e3-86d0-42b8-af99-35a2e68e3d69",
            index: null,
            answer: "ĐM cấp máu cho dạ dày là ĐM mạc treo tràng trên",
            correct: false,
            questionCode: "Q240201",
            attachmentPath: null,
          },
          {
            id: "d9d7d981-61dc-433a-b450-4493dc00a357",
            index: null,
            answer: "Thành sau dạ dày liên quan đến tuyến thượng thận trái",
            correct: false,
            questionCode: "Q240201",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Tìm ý sai về dạ dày:",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "c5872382-664d-4181-98da-158416daca6d",
            index: null,
            answer: "Là phần cuối của đại tràng",
            correct: false,
            questionCode: "Q240211",
            attachmentPath: null,
          },
          {
            id: "c92f6100-a74a-4065-9bac-7eb4a22500f4",
            index: null,
            answer: "Nằm trong chậu hông bé",
            correct: false,
            questionCode: "Q240211",
            attachmentPath: null,
          },
          {
            id: "ecebd125-94e2-4d5a-a89e-3694c9120126",
            index: null,
            answer: "Liên quan với tạng sinh dục bàng quan",
            correct: false,
            questionCode: "Q240211",
            attachmentPath: null,
          },
          {
            id: "9e979147-6f2f-431b-a9fe-5614ddfcdd4c",
            index: null,
            answer: "Phúc mạc bọc tất cả trực tràng",
            correct: false,
            questionCode: "Q240211",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Tìm ý sai về trực tràng?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "a0241083-7879-4a98-957e-94c3a262173c",
            index: null,
            answer: "ĐM thân tạng C. ĐM chủ bụng",
            correct: false,
            questionCode: "Q240221",
            attachmentPath: null,
          },
          {
            id: "7df7427a-60bb-45bc-a6cb-2ca434ed2032",
            index: null,
            answer: "Thận, niệu quản trái D. Các quai ruột non",
            correct: false,
            questionCode: "Q240221",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Thành phần không liên quan đến đại tràng xuống?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "2031f7ab-858f-4960-96cf-3ef807dbe6a7",
            index: null,
            answer: "Cột trung gian thuộc vỏ thận B. Mê đạo vỏ thuộc vỏ thận",
            correct: false,
            questionCode: "Q240231",
            attachmentPath: null,
          },
          {
            id: "15b6995f-7ca1-458b-9b42-8307adeb938f",
            index: null,
            answer:
              "Nhú thận có hình nón D. Nephron hay còn gọi là tiểu thể thận",
            correct: false,
            questionCode: "Q240231",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chọn ý sai về thận",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "7c2a8494-71a3-4ffe-a207-c099b7f523d2",
            index: null,
            answer: "Động mạch sinh dục C. Động mạch bàng quang trên",
            correct: false,
            questionCode: "Q240241",
            attachmentPath: null,
          },
          {
            id: "cfd20ac1-7beb-4246-a8be-9a1638e38d35",
            index: null,
            answer: "Động mạch tử cung D. Nhánh niệu quản động mạch thận",
            correct: false,
            questionCode: "Q240241",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Niệu quản được cấp máu bởi, trừ:",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "80623176-c057-4065-80d1-d8109d2de824",
            index: null,
            answer: "Đốt sống thắt lưng I C. Đốt sống thắt lưng II",
            correct: false,
            questionCode: "Q240251",
            attachmentPath: null,
          },
          {
            id: "f98808a1-6542-430b-8d38-0e1a447e419e",
            index: null,
            answer: "Đốt sống ngực XII D. Đốt sống ngực XI",
            correct: false,
            questionCode: "Q240251",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Động mạch thận tách ra tại ngang đốt sống thắt lưng:",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "e0669a51-3ba1-4fb7-9613-a3ec8389c14f",
            index: null,
            answer: "Dây chằng rốn giữa C. Dây chằng cung mu dưới",
            correct: false,
            questionCode: "Q240261",
            attachmentPath: null,
          },
          {
            id: "5349d5a1-141f-4a66-aef2-e3560b8c6b2f",
            index: null,
            answer: "Dây chằng ngang đáy chậu D. Dây chằng rốn trong",
            correct: false,
            questionCode: "Q240261",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Đỉnh bàng quang là nơi bám của:",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "cbcb9aab-511d-4402-99d1-5203f04a75b1",
            index: null,
            answer: "Đóng góp 30% lượng tinh dịch",
            correct: false,
            questionCode: "Q240271",
            attachmentPath: null,
          },
          {
            id: "032a8ec3-8027-4218-bf51-8eed45d40fed",
            index: null,
            answer: "Tác động đến khả năng di chuyển tinh trùng",
            correct: false,
            questionCode: "Q240271",
            attachmentPath: null,
          },
          {
            id: "6098b040-7fe6-4d62-8283-7ad5d3328243",
            index: null,
            answer: "Ức chế miễn dịch đường sinh dục nữ",
            correct: false,
            questionCode: "Q240271",
            attachmentPath: null,
          },
          {
            id: "95587ded-94fd-4546-ad12-ccc9c2c46fef",
            index: null,
            answer: "Hình tháp",
            correct: false,
            questionCode: "Q240271",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chọn câu sai: Tuyến tinh",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "7cfa3c75-021a-4587-a0c8-e8b03b9a8707",
            index: null,
            answer: "Dương vật gồm rễ, thana, đầu dương vật",
            correct: false,
            questionCode: "Q240281",
            attachmentPath: null,
          },
          {
            id: "9dc1b718-af04-4c1f-9294-e73004a3435b",
            index: null,
            answer: "Có 3 khối mô cương",
            correct: false,
            questionCode: "Q240281",
            attachmentPath: null,
          },
          {
            id: "fa58ae22-5b3f-45c8-9655-95cb2621497c",
            index: null,
            answer: "2 khối mô cương vật xốp và 1 khối mô cương vật hang",
            correct: false,
            questionCode: "Q240281",
            attachmentPath: null,
          },
          {
            id: "d04337e7-88f2-4206-8091-fdd949c9c5f3",
            index: null,
            answer: "Phần sau vật xốp phình to thành hành dương vật",
            correct: false,
            questionCode: "Q240281",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chọn sai: Dương vật",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "5e246cd6-996b-46ed-be72-ae689a1ad966",
            index: null,
            answer: "Dây chằng rộng C. Dây chằng tròn",
            correct: false,
            questionCode: "Q240291",
            attachmentPath: null,
          },
          {
            id: "9cff3f42-e80e-4152-ade4-3ef0026e9f0f",
            index: null,
            answer: "Dây chằng tử cung-cùng D. Dây chằng sau cổ tử cung",
            correct: false,
            questionCode: "Q240291",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Phương tiện giữ tử cung tại chỗ trừ:",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "d0df43c7-f4c7-4949-9288-069ac5bd532c",
            index: null,
            answer: "Eo vòi là nơi xảy ra chửa ngoài dạ con",
            correct: false,
            questionCode: "Q240301",
            attachmentPath: null,
          },
          {
            id: "7750ba41-ee62-496c-846f-2c3faa90115a",
            index: null,
            answer: "Có lỗ mở vào thành bụng trong",
            correct: false,
            questionCode: "Q240301",
            attachmentPath: null,
          },
          {
            id: "fb5d5c7b-79c4-45ed-a5e4-fe284a20222e",
            index: null,
            answer: "Là cơ quan duy nhất nằm trong hố phúc mạc",
            correct: false,
            questionCode: "Q240301",
            attachmentPath: null,
          },
          {
            id: "49dd1351-1243-43aa-bde7-bc240ddcbb77",
            index: null,
            answer: "Đầu vòi là nơi bám của d/c treo buồng trứng",
            correct: false,
            questionCode: "Q240301",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chọn ý sai về buồng trứng?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "a8d84287-8250-4e2b-8a07-29e79788ea08",
            index: null,
            answer:
              "Dải vỏ - tủy trước, bên dẫn truyền cảm giác bản thể không ý thức",
            correct: false,
            questionCode: "Q240311",
            attachmentPath: null,
          },
          {
            id: "2dda33d7-3861-48a8-af44-cc7f3d1beee8",
            index: null,
            answer: "Dải tủy tiểu não trước, sau dẫn truyền vận động có ý thức",
            correct: false,
            questionCode: "Q240311",
            attachmentPath: null,
          },
          {
            id: "e6a53aa0-3a01-4e49-b7ef-0ade3614e2ad",
            index: null,
            answer: "Dải tủy - đồi thị trước dẫn truyền cảm giác đau, nhiệt",
            correct: false,
            questionCode: "Q240311",
            attachmentPath: null,
          },
          {
            id: "6cd8cdd5-e04b-47f7-9b0a-bbecb2475175",
            index: null,
            answer: "Bó thon, bó chêm dẫn truyền cảm giác xúc giác tinh tế",
            correct: false,
            questionCode: "Q240311",
            attachmentPath: null,
          },
        ],
        explain: null,
        question:
          "Chọn câu đúng về hình thể trong của tủy sống? (Không nhớ là có hay không???)",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "c0cb9976-0a5e-4b40-b476-58ce9b8fefed",
            index: null,
            answer: "Nằm trong đại não",
            correct: false,
            questionCode: "Q240321",
            attachmentPath: null,
          },
          {
            id: "6dd3dd75-76f8-4cd4-afbc-a08845d225e9",
            index: null,
            answer: "Nhân đuôi có 3 phần: Đầu, thân, đuôi",
            correct: false,
            questionCode: "Q240321",
            attachmentPath: null,
          },
          {
            id: "655b82a1-d5be-4509-a381-9c038f2aef61",
            index: null,
            answer:
              "Nhân bèo chia thành 3 khối: bèo sẫm, cầu nhạt trong, cầu nhạt ngoài",
            correct: false,
            questionCode: "Q240321",
            attachmentPath: null,
          },
          {
            id: "916b5f44-0d07-4e36-a670-6d2619d64288",
            index: null,
            answer: "Vùng vỏ là cơ sở mọi hoạt động tinh thần",
            correct: false,
            questionCode: "Q240321",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chọn ý sai về chất xám đại não?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "d808cb6d-60b0-4084-b70c-9050b1e639a2",
            index: null,
            answer: "Hồi đai vs hồi trán trong C. Hồi đai vs thể trai",
            correct: false,
            questionCode: "Q240331",
            attachmentPath: null,
          },
          {
            id: "92340e8d-3215-41af-97a2-9ebfc34b060f",
            index: null,
            answer: "Hồi trước chêm vs hồi đai D. Hồi cạnh hải mã vs hồi lưỡi",
            correct: false,
            questionCode: "Q240331",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Rãnh đai ngăn cách gì?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "16bc0020-d2d2-4a94-90cd-256393081db4",
            index: null,
            answer:
              "Hồi trán dưới vs hồi trán trên C. Hồi thái dương trên vs hồi thái dương dưới",
            correct: false,
            questionCode: "Q240341",
            attachmentPath: null,
          },
          {
            id: "14cf5ae9-b35c-47ee-bdd7-adb325d3a7d5",
            index: null,
            answer:
              "Hồi trán dưới vs hồi trán giữa D. Hồi thái dương chẩm ngoài vs hồi trán dưới",
            correct: false,
            questionCode: "Q240341",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Rãnh bên của đại não ngăn cách gì?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "f64723fc-92f0-4627-8fb2-e336ddd6ad92",
            index: null,
            answer: "Là thần kinh vận động và tự chủ",
            correct: false,
            questionCode: "Q240351",
            attachmentPath: null,
          },
          {
            id: "4a756aa7-b6ce-433e-80c3-952e0793e749",
            index: null,
            answer: "Nguyên ủy là nhân TK vận nhãn ở hành não",
            correct: false,
            questionCode: "Q240351",
            attachmentPath: null,
          },
          {
            id: "cf5ec9a8-f9b2-4f12-b3f2-78a7d479d86c",
            index: null,
            answer: "Chạy ra sau qua thành bên xoang hang",
            correct: false,
            questionCode: "Q240351",
            attachmentPath: null,
          },
          {
            id: "60f21300-40ce-46ba-9484-12dcf19c82f3",
            index: null,
            answer: "Chi phối 5 cơ vận nhãn",
            correct: false,
            questionCode: "Q240351",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Chọn ý đúng về thần kinh vận nhãn?",
        attachmentPath: null,
        explainFilePath: null,
      },
      {
        id: null,
        code: null,
        type: 0,
        answers: [
          {
            id: "8721e185-bca5-4b01-8d3d-77e251f71dc2",
            index: null,
            answer: "Khoang bụng C. Hậu cung mạc nối",
            correct: false,
            questionCode: "Q240361",
            attachmentPath: null,
          },
          {
            id: "882f9722-36ef-45e1-8123-e03afe2fd49b",
            index: null,
            answer: "Túi mạc nối D. Ổ phúc mạc",
            correct: false,
            questionCode: "Q240361",
            attachmentPath: null,
          },
        ],
        explain: null,
        question: "Thủng mặt sau dạ dày, dịch chảy đi đâu?",
        attachmentPath: null,
        explainFilePath: null,
      },
    ],
    createdDate: 1732548780143,
    updatedDate: 1732548780143,
    createdBy: "hoangcm22.it@gmail.com",
    updatedBy: "hoangcm22.it@gmail.com",
  },
  success: true,
};

export const examFetchData = {
  status: "OK",
  message: "Exam has started.",
  data: {
    id: "d8594d2e-21ae-4113-8f45-c4faac89f082&65219833-11cb-47b6-8049-dc686a632991",
    examCode: "Q24001",
    examSessionId: "d8594d2e-21ae-4113-8f45-c4faac89f082",
    classCode: null,
    examSessionAuthor: "hoangcm22.it@gmail.com",
    examRandomCode: "Q2400101",
    studentId: "65219833-11cb-47b6-8049-dc686a632991",
    studentName: null,
    studentCode: null,
    studentEmail: "hoangcm22.it@gmail.com",
    timeTracking: 0.0,
    score: 0.0,
    startAt: 1733032138956,
    submitAt: 1733032138956,
    correctAnswer: 0,
    correctQuestion: 0,
    wrongAnswer: 0,
    wrongQuestion: 0,
    notAnswer: 0,
    rank: null,
    questionResults: [
      {
        id: null,
        code: null,
        question: "Chọn ý sai về túi mật?",
        answers: [
          {
            id: "e08a2763-1e15-4814-919f-13e73dfc20ec",
            questionCode: "Q24081",
            answer: "Có 1 đáy, 1 thân, không có cổ",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "b2162295-2371-4b0a-a30a-7bc736e5e106",
            questionCode: "Q24081",
            answer: "Ống túi mật hợp vs ống gan chung thành ống mật chủ",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "15928e94-53a7-40ab-8fda-5d495f748269",
            questionCode: "Q24081",
            answer: "Ống túi mật và túi mật là đường mật phụ",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "c0fb8fe3-efd8-4b89-b889-72b83ea6ffe2",
            questionCode: "Q24081",
            answer:
              "Đáy túi mật là điểm giao bờ ngoài cơ thẳng bụng vs bờ sườn",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Thủng mặt sau dạ dày, dịch chảy đi đâu?",
        answers: [
          {
            id: "8721e185-bca5-4b01-8d3d-77e251f71dc2",
            questionCode: "Q240361",
            answer: "Khoang bụng C. Hậu cung mạc nối",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "882f9722-36ef-45e1-8123-e03afe2fd49b",
            questionCode: "Q240361",
            answer: "Túi mạc nối D. Ổ phúc mạc",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Chỉ ra đặc điểm đúng nhất của ruột non?",
        answers: [
          {
            id: "603275ba-3cb1-4db1-8eb9-f1e0e8d8d80c",
            questionCode: "Q240191",
            answer: "Nhận máu từ ĐM mạc treo tràng trên",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "b10e1122-2824-4e13-b75d-74c4d16b2bfc",
            questionCode: "Q240191",
            answer: "Được chi phối bởi một phần đám rối mạc treo tràng trên",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "b63befa3-4971-44a1-af68-9ce45d27de46",
            questionCode: "Q240191",
            answer: "Tất cả đều đúng",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "178b8adf-4239-4a32-83d6-10bf20570d45",
            questionCode: "Q240191",
            answer: "Có dịch tụy, dịch mật và dịch vị",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Chọn ý sai về phúc mạc?",
        answers: [
          {
            id: "a163a281-1775-487b-b822-9c3a9ee7a6a9",
            questionCode: "Q24061",
            answer:
              "Dây chằng gan – tá tràng che toàn bộ thành phần vào cửa gan",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "7414a33c-36f2-4563-a70f-b0e30341ec15",
            questionCode: "Q24061",
            answer: "Mạc nối lớn gồm 2 lá dùng để dự trữ mỡ",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "b430aed8-62de-431a-a09a-55c6036e70b6",
            questionCode: "Q24061",
            answer: "Mạc treo hỗng tràng ít mỡ nhất",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "1fd0ef52-9726-42f7-8fb1-722aa674ad2e",
            questionCode: "Q24061",
            answer:
              "Mạc nối nhỏ chạy từ gan tới bờ cong nhỏ dạ dày và hành tá tràng",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Chọn câu sai về khí quản?",
        answers: [
          {
            id: "ec34291c-5e12-46ca-ad2b-7b19fdfb6e4d",
            questionCode: "Q24001",
            answer: "Tận hết tại cựa khí quản",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "18035cf7-b31d-448b-acde-558213667364",
            questionCode: "Q24001",
            answer: "Từ ngang mức đốt sống cổ V đến đĩa gian đốt sống N IV-V",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "7920a2c9-26e4-4064-8445-9d4127551252",
            questionCode: "Q24001",
            answer: "Chạy tiếp theo thanh quản từ bờ dưới sụn nhẫn",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "fa344f41-4cd9-48cf-90a3-358b8d84c38a",
            questionCode: "Q24001",
            answer: "Tạo bởi các vòng sụn xếp chồng lên nhau",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Mạc treo nào không có thật?",
        answers: [
          {
            id: "bd997aa8-f7d8-4df1-bb11-1b6ba068eb89",
            questionCode: "Q24071",
            answer: "Mạc treo đại tràng lên C. Mạc treo đại tràng sigma",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "678070b4-d0b8-4a1f-9297-5e32b51555ad",
            questionCode: "Q24071",
            answer: "Mạc treo ruột thừa D. Mạc treo đại tràng ngang",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Động mạch thận tách ra tại ngang đốt sống thắt lưng:",
        answers: [
          {
            id: "f98808a1-6542-430b-8d38-0e1a447e419e",
            questionCode: "Q240251",
            answer: "Đốt sống ngực XII D. Đốt sống ngực XI",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "80623176-c057-4065-80d1-d8109d2de824",
            questionCode: "Q240251",
            answer: "Đốt sống thắt lưng I C. Đốt sống thắt lưng II",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Tìm ý sai về tụy?",
        answers: [
          {
            id: "1d91217e-e935-4996-a0b3-0e423e7f9a6e",
            questionCode: "Q240181",
            answer: "Có nhiều ĐM đến cấp máu D. Do hệ TK thực vật chi phối",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "aac9e638-0afa-4375-8f78-920869c3b51a",
            questionCode: "Q240181",
            answer:
              "Chỉ là một tuyến ngoại tiết C. Có ống tiết đổ vào tá tràng",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Chọn ý sai về dạ dày?",
        answers: [
          {
            id: "5def17b8-873c-4a9c-b590-4dda8b104b0e",
            questionCode: "Q24091",
            answer: "Là mặt trước của hậu cung mạc nối",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "3d7ed12c-3005-485b-aeff-67aedaa44496",
            questionCode: "Q24091",
            answer: "Gồm 3 lớp cơ: thẳng ngoài – vòng giữa – chéo trong cùng",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "4281483b-24ec-451e-942d-8ddc3a7d306d",
            questionCode: "Q24091",
            answer: "Khuyết góc là giao bờ trái tá tràng vs bờ cong lớn",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "37fef4d6-4316-48f9-8185-c28ed3a92332",
            questionCode: "Q24091",
            answer:
              "Bờ trái thực quản liên tiếp với bờ cong lớn tại khuyết tâm vị",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Hỗng tràng khác với hồi tràng ở điểm :",
        answers: [
          {
            id: "5c6ff43c-e558-419d-902c-eb21ee79aed1",
            questionCode: "Q240131",
            answer:
              "Ít bề mặt tiêu hoá hơn C. Đường kính nhỏ hơn E. Nhung mao ít hơn",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "f736a4f5-5682-4aca-9115-80e1b9549c72",
            questionCode: "Q240131",
            answer: "Nhung mao nhiều hơn D. Thành mỏng hơn.",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Niệu quản được cấp máu bởi, trừ:",
        answers: [
          {
            id: "7c2a8494-71a3-4ffe-a207-c099b7f523d2",
            questionCode: "Q240241",
            answer: "Động mạch sinh dục C. Động mạch bàng quang trên",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "cfd20ac1-7beb-4246-a8be-9a1638e38d35",
            questionCode: "Q240241",
            answer: "Động mạch tử cung D. Nhánh niệu quản động mạch thận",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Một khối u ở mỏm móc đầu tụy có thể gây chèn ép:",
        answers: [
          {
            id: "41e3920f-07b7-4727-8757-d51ab2cab195",
            questionCode: "Q240111",
            answer: "Ống mật chủ C. TM mạc treo tràng trên",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "20c2cf69-5557-4000-b126-6ef9ba049d39",
            questionCode: "Q240111",
            answer: "TM cửa D. Ống tụy E. Bóng gan-tụy",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Chọn ý sai về buồng trứng?",
        answers: [
          {
            id: "49dd1351-1243-43aa-bde7-bc240ddcbb77",
            questionCode: "Q240301",
            answer: "Đầu vòi là nơi bám của d/c treo buồng trứng",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "7750ba41-ee62-496c-846f-2c3faa90115a",
            questionCode: "Q240301",
            answer: "Có lỗ mở vào thành bụng trong",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "fb5d5c7b-79c4-45ed-a5e4-fe284a20222e",
            questionCode: "Q240301",
            answer: "Là cơ quan duy nhất nằm trong hố phúc mạc",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "d0df43c7-f4c7-4949-9288-069ac5bd532c",
            questionCode: "Q240301",
            answer: "Eo vòi là nơi xảy ra chửa ngoài dạ con",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Chọn câu sai về cơ hoành?",
        answers: [
          {
            id: "2020d0ce-e9fd-4f32-af5c-1e605fd30d76",
            questionCode: "Q24031",
            answer:
              "Bờ gân trong trụ phải, trụ trái tạo nên dây chằng cung giữa",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "867213e6-5962-48a4-b6e4-6611fab5ba2a",
            questionCode: "Q24031",
            answer: "Là cơ hô hấp",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "99a2b612-1c44-41bc-a10e-d3c622b329e4",
            questionCode: "Q24031",
            answer: "Lỗ ĐM chủ nằm ngang mức bờ dưới đốt sống N XII",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "6a50a91e-28a4-4be8-94f8-5d87b5046b41",
            questionCode: "Q24031",
            answer: "Gân trung tâm là nguyên ủy của cơ hoành",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Các mô tả sau đây về ĐM mạc treo tràng dưới đều đúng, trừ:",
        answers: [
          {
            id: "9b644e83-e453-42f3-bce4-e287904f2de4",
            questionCode: "Q240101",
            answer: "Đi sang trái ĐM chủ rồi bắt chéo ĐM chậu chung trái",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "4df3acfe-bee1-4d9a-bfbe-8321e848993e",
            questionCode: "Q240101",
            answer: "Tận cũng bởi ĐM trực tràng trên",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "c78d6ea5-49d3-48ff-b63e-9b1d5ccadbff",
            questionCode: "Q240101",
            answer:
              "Có đường kính và kích thước lớn hơn ĐM mạc treo tràng trên",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "9fc2f926-0d7a-448b-9325-485fcd49c614",
            questionCode: "Q240101",
            answer: "Tách ra từ ĐM chủ bụng ở ngang đốt sống thắt lưng III",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Rãnh bên của đại não ngăn cách gì?",
        answers: [
          {
            id: "14cf5ae9-b35c-47ee-bdd7-adb325d3a7d5",
            questionCode: "Q240341",
            answer:
              "Hồi trán dưới vs hồi trán giữa D. Hồi thái dương chẩm ngoài vs hồi trán dưới",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "16bc0020-d2d2-4a94-90cd-256393081db4",
            questionCode: "Q240341",
            answer:
              "Hồi trán dưới vs hồi trán trên C. Hồi thái dương trên vs hồi thái dương dưới",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Đỉnh bàng quang là nơi bám của:",
        answers: [
          {
            id: "5349d5a1-141f-4a66-aef2-e3560b8c6b2f",
            questionCode: "Q240261",
            answer: "Dây chằng ngang đáy chậu D. Dây chằng rốn trong",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "e0669a51-3ba1-4fb7-9613-a3ec8389c14f",
            questionCode: "Q240261",
            answer: "Dây chằng rốn giữa C. Dây chằng cung mu dưới",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "ĐM nào không phải nhánh bên của ĐM chủ?",
        answers: [
          {
            id: "70b0fa89-ed07-4649-8313-dcf5ffbf55fc",
            questionCode: "Q24051",
            answer: "ĐM vành phải, trái D. ĐM cảnh chung phải",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "16e13304-5405-4f9f-b736-39feb1d2091f",
            questionCode: "Q24051",
            answer: "ĐM thân cánh tay đầu C. ĐM thận phải, trái",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Tìm ý sai về trực tràng?",
        answers: [
          {
            id: "c5872382-664d-4181-98da-158416daca6d",
            questionCode: "Q240211",
            answer: "Là phần cuối của đại tràng",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "9e979147-6f2f-431b-a9fe-5614ddfcdd4c",
            questionCode: "Q240211",
            answer: "Phúc mạc bọc tất cả trực tràng",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "c92f6100-a74a-4065-9bac-7eb4a22500f4",
            questionCode: "Q240211",
            answer: "Nằm trong chậu hông bé",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "ecebd125-94e2-4d5a-a89e-3694c9120126",
            questionCode: "Q240211",
            answer: "Liên quan với tạng sinh dục bàng quan",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question:
          "Điểm cao nhất của đỉnh phổi nhô lên trên đầu trước xương sườn I, xương đòn, cách",
        answers: [
          {
            id: "0d2a8267-c225-417b-bc0b-4acd91dae5f6",
            questionCode: "Q24021",
            answer: "4 cm – 3 cm – 5 cm D. 5 cm – 4 cm – 3 cm",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "3cdbee44-bb94-43c0-8055-47dad44d07e6",
            questionCode: "Q24021",
            answer: "3 cm – 4 cm – 5cm C. 5 cm – 3 cm – 4 cm",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Rốn gan gồm có các thành phần sau, trừ:",
        answers: [
          {
            id: "a4180f4d-3c35-4325-8ba2-4eaf1c3fccd3",
            questionCode: "Q240141",
            answer: "Ống mật D. Rễ mạc nối nhỏ",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "18ba6db0-0938-4b16-99e5-4acfd7b663d3",
            questionCode: "Q240141",
            answer:
              "Tĩnh mạch cửa C. Động mạch gan chung E. Động mạch gan riêng",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Tất cả các mô tả sau về đại tràng xuống đều đúng trừ",
        answers: [
          {
            id: "ee0c5b4d-c396-45cf-9237-445fb4d7e79a",
            questionCode: "Q240121",
            answer: "Nó dược cấp máu bởi ĐM mạc treo tràng dưới",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "1e645c18-e0bc-443c-92be-21a8aed3968c",
            questionCode: "Q240121",
            answer:
              "Nó tiếp nhận các sợi đối giao cảm trước hạch từ TK lang thang",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "cd31e9d0-ee4a-4d22-8a78-282f3c745dc7",
            questionCode: "Q240121",
            answer:
              "Nó hấp thu nước để biến dịch chứa bên trong thành phân đặc",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "06563ef0-06df-46cf-9f4a-2833f40d28d4",
            questionCode: "Q240121",
            answer: "Nó có dải sán đại tràng và túi thừa mạc nối",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Chọn câu sai: Tuyến tinh",
        answers: [
          {
            id: "032a8ec3-8027-4218-bf51-8eed45d40fed",
            questionCode: "Q240271",
            answer: "Tác động đến khả năng di chuyển tinh trùng",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "95587ded-94fd-4546-ad12-ccc9c2c46fef",
            questionCode: "Q240271",
            answer: "Hình tháp",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "6098b040-7fe6-4d62-8283-7ad5d3328243",
            questionCode: "Q240271",
            answer: "Ức chế miễn dịch đường sinh dục nữ",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "cbcb9aab-511d-4402-99d1-5203f04a75b1",
            questionCode: "Q240271",
            answer: "Đóng góp 30% lượng tinh dịch",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Chọn ý đúng về thần kinh vận nhãn?",
        answers: [
          {
            id: "f64723fc-92f0-4627-8fb2-e336ddd6ad92",
            questionCode: "Q240351",
            answer: "Là thần kinh vận động và tự chủ",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "4a756aa7-b6ce-433e-80c3-952e0793e749",
            questionCode: "Q240351",
            answer: "Nguyên ủy là nhân TK vận nhãn ở hành não",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "cf5ec9a8-f9b2-4f12-b3f2-78a7d479d86c",
            questionCode: "Q240351",
            answer: "Chạy ra sau qua thành bên xoang hang",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "60f21300-40ce-46ba-9484-12dcf19c82f3",
            questionCode: "Q240351",
            answer: "Chi phối 5 cơ vận nhãn",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Ở mặt tạng của gan, thùy vuông liên quan tới?",
        answers: [
          {
            id: "ec20c765-ae2b-4087-9d90-d22534322ed1",
            questionCode: "Q240171",
            answer: "Dạ dày C. Đoạn đầu tá tràng",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "99d45723-5e30-44ec-8471-e06883b43735",
            questionCode: "Q240171",
            answer: "Góc đại tràng phải D. Dạ dày - tá tụy",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Chọn ý sai về thận",
        answers: [
          {
            id: "15b6995f-7ca1-458b-9b42-8307adeb938f",
            questionCode: "Q240231",
            answer:
              "Nhú thận có hình nón D. Nephron hay còn gọi là tiểu thể thận",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "2031f7ab-858f-4960-96cf-3ef807dbe6a7",
            questionCode: "Q240231",
            answer: "Cột trung gian thuộc vỏ thận B. Mê đạo vỏ thuộc vỏ thận",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Phương tiện giữ tử cung tại chỗ trừ:",
        answers: [
          {
            id: "9cff3f42-e80e-4152-ade4-3ef0026e9f0f",
            questionCode: "Q240291",
            answer: "Dây chằng tử cung-cùng D. Dây chằng sau cổ tử cung",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "5e246cd6-996b-46ed-be72-ae689a1ad966",
            questionCode: "Q240291",
            answer: "Dây chằng rộng C. Dây chằng tròn",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Chọn ý sai về chất xám đại não?",
        answers: [
          {
            id: "655b82a1-d5be-4509-a381-9c038f2aef61",
            questionCode: "Q240321",
            answer:
              "Nhân bèo chia thành 3 khối: bèo sẫm, cầu nhạt trong, cầu nhạt ngoài",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "c0cb9976-0a5e-4b40-b476-58ce9b8fefed",
            questionCode: "Q240321",
            answer: "Nằm trong đại não",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "916b5f44-0d07-4e36-a670-6d2619d64288",
            questionCode: "Q240321",
            answer: "Vùng vỏ là cơ sở mọi hoạt động tinh thần",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "6dd3dd75-76f8-4cd4-afbc-a08845d225e9",
            questionCode: "Q240321",
            answer: "Nhân đuôi có 3 phần: Đầu, thân, đuôi",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Hậu cung mạc nối có các đặc điểm sau, trừ:",
        answers: [
          {
            id: "293ba114-296d-4fc0-8b2f-c96206fda13f",
            questionCode: "Q240151",
            answer: "Thành dưới : dạ dày",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "516d3e5e-d1bb-4757-b315-9e12319a3413",
            questionCode: "Q240151",
            answer: "Bờ trên liên quan đến cơ hoành",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "c5db83ab-ae74-4f03-b369-22a44f436557",
            questionCode: "Q240151",
            answer: "Thành sau liên quan đến tụy, thận trái",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "7b83c6d2-a2ac-40fb-b6d2-9849291aa31f",
            questionCode: "Q240151",
            answer: "Thành trái liên quan đến lách , dây chằng tụy lách",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question:
          "Trình tự sắp xếp các thành phần trong cửa gan từ trước ra sau là:",
        answers: [
          {
            id: "e593ff62-879e-4497-88a2-3984529762d0",
            questionCode: "Q240161",
            answer:
              "Nhánh phải và trái của ĐM gan, các ống gan, 2 nhánh TM cửa",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "7f350a54-4a80-4cee-8655-1092609a2177",
            questionCode: "Q240161",
            answer:
              "Các ống gan, nhánh phải và trái của ĐM gan, 2 nhánh TM cửa",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "3e758541-8e4a-4606-8f42-e81131a4c940",
            questionCode: "Q240161",
            answer:
              "Các ống gan, 2 nhánh TM cửa, nhánh phải và trái của ĐM gan",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "e18a00b0-d677-456b-b14e-b265dcdc5451",
            questionCode: "Q240161",
            answer:
              "Nhánh phải và trái của ĐM gan , 2 nhánh TM cửa, các ống gan",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Chọn câu đúng về ổ ngoại tâm mạc?",
        answers: [
          {
            id: "8785f9f1-9fe3-4a69-ae3d-0ce82fb1896f",
            questionCode: "Q24041",
            answer: "Bình thường trong ổ ngoại tâm mạc không chứa dịch",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "194c5235-ed61-4e2d-be16-6f5b24d2ab9d",
            questionCode: "Q24041",
            answer: "Nằm giữa 2 lá của ngoại tâm mạc sợi",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "2dcdfbe5-6931-4e9a-822e-2f3b76814a40",
            questionCode: "Q24041",
            answer: "Là khoang thật",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "5640a7e4-511b-46ff-94c5-feb6561b9b3d",
            questionCode: "Q24041",
            answer: "Khi viêm gây tràn dịch ngoại tâm mạc",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Chọn câu đúng về phế quản chính?",
        answers: [
          {
            id: "562d71b6-eb8b-40e5-861f-fc36a9cc3a2a",
            questionCode: "Q24011",
            answer: "Sau khi vào rốn phổi, phế quản chính trái tách ra 3 nhánh",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "3c558b7f-1f87-4a0f-8901-8b58cd4ccec8",
            questionCode: "Q24011",
            answer: "Sau khi vào rốn phổi, phế quản chính phải tách ra 3 nhánh",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "8e0e0b30-0ba7-4531-965b-5eaf1a054ad9",
            questionCode: "Q24011",
            answer: "Bên phải rộng hơn, ngắn hơn, thẳng đứng hơn bên trái",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "6e333a97-20e7-4fea-9a88-23f44811684a",
            questionCode: "Q24011",
            answer: "Dị vật đường thở thường rơi vào phế quản chính trái",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Tìm ý sai về dạ dày:",
        answers: [
          {
            id: "373362e3-86d0-42b8-af99-35a2e68e3d69",
            questionCode: "Q240201",
            answer: "ĐM cấp máu cho dạ dày là ĐM mạc treo tràng trên",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "bce5c8ec-7bfc-46cb-9b83-c5eb3343d80e",
            questionCode: "Q240201",
            answer: "TK chi phối cho dạ dày từ đám rối tạng và TK lang thang",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "d9d7d981-61dc-433a-b450-4493dc00a357",
            questionCode: "Q240201",
            answer: "Thành sau dạ dày liên quan đến tuyến thượng thận trái",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "5fd29218-34d4-432a-97ea-e3faf56b9802",
            questionCode: "Q240201",
            answer: "Lớp cơ phân bố không đều ở tất cả các phần của dạ dày",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Rãnh đai ngăn cách gì?",
        answers: [
          {
            id: "92340e8d-3215-41af-97a2-9ebfc34b060f",
            questionCode: "Q240331",
            answer: "Hồi trước chêm vs hồi đai D. Hồi cạnh hải mã vs hồi lưỡi",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "d808cb6d-60b0-4084-b70c-9050b1e639a2",
            questionCode: "Q240331",
            answer: "Hồi đai vs hồi trán trong C. Hồi đai vs thể trai",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Thành phần không liên quan đến đại tràng xuống?",
        answers: [
          {
            id: "7df7427a-60bb-45bc-a6cb-2ca434ed2032",
            questionCode: "Q240221",
            answer: "Thận, niệu quản trái D. Các quai ruột non",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "a0241083-7879-4a98-957e-94c3a262173c",
            questionCode: "Q240221",
            answer: "ĐM thân tạng C. ĐM chủ bụng",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question: "Chọn sai: Dương vật",
        answers: [
          {
            id: "9dc1b718-af04-4c1f-9294-e73004a3435b",
            questionCode: "Q240281",
            answer: "Có 3 khối mô cương",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "fa58ae22-5b3f-45c8-9655-95cb2621497c",
            questionCode: "Q240281",
            answer: "2 khối mô cương vật xốp và 1 khối mô cương vật hang",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "d04337e7-88f2-4206-8091-fdd949c9c5f3",
            questionCode: "Q240281",
            answer: "Phần sau vật xốp phình to thành hành dương vật",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "7cfa3c75-021a-4587-a0c8-e8b03b9a8707",
            questionCode: "Q240281",
            answer: "Dương vật gồm rễ, thana, đầu dương vật",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
      {
        id: null,
        code: null,
        question:
          "Chọn câu đúng về hình thể trong của tủy sống? (Không nhớ là có hay không???)",
        answers: [
          {
            id: "a8d84287-8250-4e2b-8a07-29e79788ea08",
            questionCode: "Q240311",
            answer:
              "Dải vỏ - tủy trước, bên dẫn truyền cảm giác bản thể không ý thức",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "e6a53aa0-3a01-4e49-b7ef-0ade3614e2ad",
            questionCode: "Q240311",
            answer: "Dải tủy - đồi thị trước dẫn truyền cảm giác đau, nhiệt",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "2dda33d7-3861-48a8-af44-cc7f3d1beee8",
            questionCode: "Q240311",
            answer: "Dải tủy tiểu não trước, sau dẫn truyền vận động có ý thức",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
          {
            id: "6cd8cdd5-e04b-47f7-9b0a-bbecb2475175",
            questionCode: "Q240311",
            answer: "Bó thon, bó chêm dẫn truyền cảm giác xúc giác tinh tế",
            attachmentPath: null,
            correct: false,
            chosen: false,
          },
        ],
        explain: null,
      },
    ],
    submitted: false,
  },
  success: true,
};
